export const APP_CONFIG = {
    MAX_HEADS: 50,
    MAX_STEPS_INSTANT: 100000,
    DEFAULT_DIMENSION_DESKTOP: 232,
    DEFAULT_DIMENSION_MOBILE: 160,
};

export const SKETCH_DEFAULTS = {
    MAX_HEADS: 64,
    BRANCH_PROBABILITY: 0.05,
    ALPHA: 0.1,
    LINE_WIDTH: 0.5,
    SCALE_FACTOR: 0.8,
    MOMENTUM: 0.5,
};
